apiVersion: v1
kind: Service
metadata:
  name: revue-frontend
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: revue-frontend
  ports:
    - name: web
      port: 8080
      targetPort: 8080