apiVersion: v1
kind: Service
metadata:
  name: revue-notification-db
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: revue-notification-db
  ports:
    - name: notifdbport
      port: 27017
      targetPort: 27017