apiVersion: apps/v1
kind: Deployment
metadata:
  name: revue-monitoring
  namespace: default
spec:
  selector:
    matchLabels:
      app: revue-monitoring
  template:
    metadata:
      labels:
        app: revue-monitoring
    spec:
      containers:
        - name: revue-monitoring
          image: letsdothisshared/revue-monitoring:test
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
              name: monitoringport
              protocol: TCP
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "700m"
          env:
            - name: KUBERNETES_SERVICE_HOST
              value: "true"
      restartPolicy: Always