apiVersion: apps/v1
kind: Deployment
metadata:
  name: revue-zookeeper-2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revue-zookeeper-2
  template:
    metadata:
      labels:
        app: revue-zookeeper-2
    spec:
      containers:
        - env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          image: bitnami/zookeeper:latest
          name: revue-zookeeper-2
          ports:
            - containerPort: 2181
              protocol: TCP
      restartPolicy: Always
