apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-address-pool-traefik
  namespace: metallb-system
spec:
  addresses:
    - 192.168.5.49/32
  avoidBuggyIPs: true
  serviceAllocation:
    priority: 1
    namespaces:
      - default
    serviceSelectors:
      - matchExpressions:
          - {key: app.kubernetes.io/name, operator: In, values: [traefik]}