apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system  # Same MetalLB namespace
spec:
  ipAddressPools:
  - ip-address-pool
  - ip-address-pool-media-server
