apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-address-pool-media-server
  namespace: metallb-system
spec:
  addresses:
    - 192.168.5.101/32
  avoidBuggyIPs: true
  serviceAllocation:
    priority: 1
    namespaces:
      - default
    serviceSelectors:
      - matchExpressions:
          - {key: app, operator: In, values: [revue-media-server]}