apiVersion: v1
kind: Service
metadata:
  name: revue-kafka-ui
  namespace: default
  labels:
    app: revue-kafka-ui
spec:
  type: LoadBalancer
  selector:
    app: revue-kafka-ui
  ports:
    - name: kafkaui
      port: 8082
      targetPort: 8080
