apiVersion: apps/v1
kind: Deployment
metadata:
  name: revue-alarm-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revue-alarm-db
  template:
    metadata:
      labels:
        app: revue-alarm-db
    spec:
      containers:
        - name: revue-alarm-db
          image: mongo
          env:
            - name: MONGO_INITDB_DATABASE
              value: alarm
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          ports:
            - containerPort: 27017
              name: alarmdbport
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: revue-alarm-data
            - mountPath: /docker-entrypoint-initdb.d/alarm-init.js
              name: revue-alarm-db-cm1
              subPath: alarm-init.js
      restartPolicy: Always
      volumes:
        - name: revue-alarm-data
          persistentVolumeClaim:
            claimName: revue-alarm-data
        - configMap:
            items:
              - key: alarm-init.js
                path: alarm-init.js
            name: revue-alarm-db-cm1
          name: revue-alarm-db-cm1
