apiVersion: apps/v1
kind: Deployment
metadata:
  name: revue-alarm
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: revue-alarm
  template:
    metadata:
      labels:
        app: revue-alarm
    spec:
      containers:
        - name: revue-alarm
          image: letsdothisshared/revue-alarm:test
          imagePullPolicy: Always
          ports:
            - containerPort: 4002
              name: alarmport
              protocol: TCP
          env:
            - name: KUBERNETES_SERVICE_HOST
              value: "true"
      restartPolicy: Always
