apiVersion: v1
kind: Service
metadata:
  name: revue-zookeeper-2
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: revue-zookeeper-2
  ports:
    - name: zookeeper2
      port: 2182
      targetPort: 2181

