apiVersion: v1
kind: Service
metadata:
  name: revue-device
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: revue-device
  ports:
    - name: deviceport
      port: 4007
      targetPort: deviceport
