apiVersion: v1
kind: Service
metadata:
  name: revue-zookeeper-1
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: revue-zookeeper-1
  ports:
    - name: zookeeper1
      port: 2181
      targetPort: 2181