apiVersion: apps/v1
kind: Deployment
metadata:
  name: revue-frontend
  namespace: default
spec:
  selector:
    matchLabels:
      app: revue-frontend
  template:
    metadata:
      labels:
        app: revue-frontend
    spec:
      containers:
        - name: revue-frontend
          image: letsdothisshared/revue-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "700m"
          readinessProbe:
            httpGet:
              port: web
              path: /
      restartPolicy: Always
