apiVersion: apps/v1
kind: Deployment
metadata:
  name: revue-log-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revue-log-db
  template:
    metadata:
      labels:
        app: revue-log-db
    spec:
      containers:
        - name: revue-log-db
          image: mongo
          env:
            - name: MONGO_INITDB_DATABASE
              value: log
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          ports:
            - containerPort: 27017
              name: logdbport
              protocol: TCP
          volumeMounts:
            - mountPath: /data/db
              name: revue-log-data
            - mountPath: /docker-entrypoint-initdb.d/history-init.js
              name: revue-log-db-cm1
              subPath: history-init.js
      restartPolicy: Always
      volumes:
        - name: revue-log-data
          persistentVolumeClaim:
            claimName: revue-log-data
        - configMap:
            items:
              - key: history-init.js
                path: history-init.js
            name: revue-log-db-cm1
          name: revue-log-db-cm1
