apiVersion: apps/v1
kind: Deployment
metadata:
  name: revue-recognition
  namespace: default
spec:
  selector:
    matchLabels:
      app: revue-recognition
  template:
    metadata:
      labels:
        app: revue-recognition
    spec:
      containers:
        - name: revue-monitoring
          image: letsdothisshared/revue-recognition:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4005
              name: recognitionport
              protocol: TCP
          env:
            - name: KUBERNETES_SERVICE_HOST
              value: "true"
            - name: RECOGNITION_PORT
              value: "4005"  # Replace with the correct port
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "700m"
      restartPolicy: Always
