apiVersion: v1
kind: Service
metadata:
  name: revue-recognition
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: revue-recognition
  ports:
    - name: recognitionport
      port: 4005
      targetPort: recognitionport
