apiVersion: v1
kind: Service
metadata:
  name: revue-alarm
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: revue-alarm
  ports:
    - name: alarmport
      port: 4002
      targetPort: alarmport
