apiVersion: v1
kind: Service
metadata:
  name: revue-alarm-db
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: revue-alarm-db
  ports:
    - name: alarmdbport
      port: 27017
      targetPort: 27017
  
