apiVersion: apps/v1
kind: Deployment
metadata:
  name: revue-device
  namespace: default
spec:
  selector:
    matchLabels:
      app: revue-device
  template:
    metadata:
      labels:
        app: revue-device
    spec:
      containers:
        - name: revue-device
          image: letsdothisshared/revue-device:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4007
              name: deviceport
              protocol: TCP
          resources:
            requests:
              cpu: "250m"
            limits:
              cpu: "700m"
          env:
            - name: KUBERNETES_SERVICE_HOST
              value: "true"
      restartPolicy: Always
