apiVersion: v1
kind: Service
metadata:
  name: revue-kafka-2
  namespace: default
  labels:
    app: revue-kafka-2
spec:
  type: LoadBalancer
  selector:
    app: revue-kafka-2
  ports:
    - name: internalkafka
      port: 9093
      targetPort: 9093
    - name: externalkafka
      port: 9095
      targetPort: 9095