apiVersion: v1
kind: Service
metadata:
  name: revue-user
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: revue-user
  ports:
    - name: userport
      port: 4006
      targetPort: userport